### ISSUE TITLE
Wrong git url for Azure IoT Hub SDK

### ISSUE THREAD

**Issue by ripenko** [Azure/azure-iot-pal-esp32#1]
Step 4 of the readme.md has wrong command to clone azure-iot
`git clone --recursive https://github.com/Azure-Samples/iot-hub-c-esp32.git azure-iot`
I think it should be 
`git clone --recursive https://github.com/Azure/azure-iot-pal-esp32.git azure-iot`

**Comment by JetstreamRoySprowl** [comment]
Fixed -- thank you!

**Comment by JetstreamRoySprowl** [comment]
Fixed and replied to.
roy

**Comment by ripenko** [comment]
thanks!
