### ISSUE TITLE
How to use direct methods on esp32

### ISSUE THREAD

**Issue by goyalhonney** [Azure/azure-iot-pal-esp32#10]
I have been trying to use direct method on Azure-esp arduino but in one of issues on that library it is mentioned that azure do not support direct method on arduino esp8266.
Wondering if direct method works on espressif esp32.
As  espressif esp32 is very new environment for me.

**Comment by Resultfactory** [comment]
Yes it works! You will have to use "IoTHubClient_LL_SetDeviceMethodCallback" to set your method callback =)

**Comment by naznaaa** [comment]
hi,
can you please provide a sample code to connect esp32 with azure iothub using espidf
