### ISSUE TITLE
Link failure with device twin simple sample

### ISSUE THREAD

**Issue by schmidtf** [Azure/azure-iot-pal-esp32#11]
ESP32-IDF: Release 3.0, cloned on 29 May 2018 (commit 64b56beff5a4d6a165bd88027f585bfe51fbb990)
Azure IOT: cloned azure-iot-pal-esp32 on 29 May 2018

Hello,

I am attempting to build the basic device twin sample in:
\esp-idf\components\azure-iot\sdk\serializer\samples\devicetwin_simplesample

using devicetwin_simplesample.c and devicetwin_simplesample.h, with a simple azure_task in my main.c,  as suggested in:

\esp-idf\components\azure-iot\sample\main\azure_main.c

However, the linker fails on the undefined references below:
[CODE]
...
CC build/xtensa-debug-module/trax.o
CC build/xtensa-debug-module/eri.o
AR build/xtensa-debug-module/libxtensa-debug-module.a
LD build/app-template.elf
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o):(.literal.Generic_IoTHubClient_SetCallbacks+0x18): undefined reference to `IoTHubClien                                         t_SetDeviceTwinCallback'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o):(.literal.Generic_IoTHubClient_SetCallbacks+0x1c): undefined reference to `IoTHubClien                                         t_SetDeviceMethodCallback'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o):(.literal.IoTHubDeviceTwin_SendReportedState_Impl+0x18): undefined reference to `IoTHu                                         bClient_SendReportedState'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o):(.literal.device_twin_simple_sample_run+0x50): undefined reference to `IoTHubClient_Cr                                         eateFromConnectionString'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o):(.literal.device_twin_simple_sample_run+0x54): undefined reference to `IoTHubClient_Se                                         tOption'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o):(.literal.device_twin_simple_sample_run+0x58): undefined reference to `IoTHubClient_De                                         stroy'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o): In function `Generic_IoTHubClient_SetCallbacks':
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:58: undefined reference to `IoTHubClient_SetDeviceTwinCallback'
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:58: undefined reference to `IoTHubClient_SetDeviceMethodCallback'
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:58: undefined reference to `IoTHubClient_SetDeviceTwinCallback'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o): In function `IoTHubDeviceTwin_SendReportedState_Impl':
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:58: undefined reference to `IoTHubClient_SendReportedState'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o): In function `IoTHubDeviceTwin_Destroy_Impl':
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:58: undefined reference to `IoTHubClient_SetDeviceTwinCallback'
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:58: undefined reference to `IoTHubClient_SetDeviceMethodCallback'
D:/esp32_projects/myapp/build/main\libmain.a(devicetwin_simplesample.o): In function `device_twin_simple_sample_run':
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:101: undefined reference to `IoTHubClient_CreateFromConnectionString'
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:114: undefined reference to `IoTHubClient_SetOption'
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:141: undefined reference to `IoTHubClient_SetDeviceTwinCallback'
D:/esp32_projects/myapp/main/devicetwin_simplesample.c:155: undefined reference to `IoTHubClient_Destroy'
collect2.exe: error: ld returned 1 exit status
make: *** [D:\ESP32_Projects\ESP32-IDF\esp-idf/make/project.mk:406: /d/esp32_projects/myapp/build/app-template.elf] Error 1
[/CODE]

Is this a azure-iot-pal-esp32 issue with supporting device twin functionality, or am I missing something?

Thank you in advance.

**Comment by schmidtf** [comment]
Can anyone can successfully build the devicetwin_simplesample?
@JetstreamRoySprowl , @Resultfactory, @Patrik-Berglund ?

**Comment by JetstreamRoySprowl** [comment]
The component.mk for the sample does not include files that are not needed for the supplied sample. You'll need to add any extra files and directories to your component.mk file.

**Comment by Patrik-Berglund** [comment]
@schmidtf Did you manage to get it working?

**Comment by schmidtf** [comment]
Thanks, @JetstreamRoySprowl.

And thank you, @Patrik-Berglund. I am still working to figure out which files and directories to include in component.mk to successfully build the device twin sample.

**Comment by BigPeteB** [comment]
@schmidtf It's been a while since this issue was opened. Were you able to get this working?

**Comment by schmidtf** [comment]
Hello @BigPeteB , yes, I believe I did modify component.mk to get it working.  Thanks!
