### ISSUE TITLE
ESP32 connection lost between cloud

### ISSUE THREAD

**Issue by omerfatih** [Azure/azure-iot-pal-esp32#2]
Hi
We are working on a project in which we are developing a bidirectional communication between a device and a cloud through ioT hub. We have downloaded the sample code that you have provided here. After the first start, things go nicely, the system works without any errors, as expected. But as some time passes, we begin to have the following error message and lose the connection. System recovers itself over some time but the time it takes to recover itself is longer than we like. What would you recommend us to do to eliminate this error message.
The error message is given below
Thanks in advance

`-> 06:30:19 PINGREQ

<- 06:30:19 PINGRESP

-> 06:34:10 PINGREQ

<- 06:34:10 PINGRESP

-> 06:38:01 PINGREQ

<- 06:38:01 PINGRESP

-> 06:41:52 PINGREQ

<- 06:41:52 PINGRESP

-> 06:45:43 PINGREQ

<- 06:45:43 PINGRESP

-> 06:49:34 PINGREQ

<- 06:49:34 PINGRESP

-> 06:53:25 PINGREQ

<- 06:53:25 PINGRESP

-> 06:57:16 PINGREQ

<- 06:57:16 PINGRESP

-> 07:01:07 PINGREQ

<- 07:01:07 PINGRESP

-> 07:04:58 PINGREQ

<- 07:04:58 PINGRESP

-> 07:08:49 PINGREQ

<- 07:08:49 PINGRESP

-> 07:12:40 PINGREQ

<- 07:12:40 PINGRESP

Error: Time:Thu Nov 16 07:14:28 2017 File:C:/msys32/home/Kayten/esp/esp-idf/components/azure-
iot/sdk/c-utility/src/xio.c Func:xio_retrieveoptions Line:280 unable to concrete_io_retrieveoptions

-> 07:14:28 DISCONNECT

Error: Time:Thu Nov 16 07:14:28 2017 File:C:/msys32/home/Kayten/esp/esp-
idf/components/azureiot/pal/src/tlsio_openssl_compact.c Func:tlsio_openssl_destroy Line:207 tlsio_openssl_destroy called while not in TLSIO_STATE_CLOSED.

Error: Time:Thu Nov 16 07:18:29 2017 File:C:/msys32/home/Kayten/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:1800 mqtt_client timed out waiting for CONNACK

Error: Time:Thu Nov 16 07:18:29 2017 File:C:/msys32/home/Kayten/esp/esp-idf/components/azure-iot/sdk/c-utility/src/xio.c Func:xio_retrieveoptions Line:280 unable to concrete_io_retrieveoptions

Error: Time:Thu Nov 16 07:18:29 2017 File:C:/msys32/home/Kayten/esp/esp-idf/components/azure-iot/pal/src/tlsio_openssl_compact.c Func:tlsio_openssl_send_async Line:476 tlsio_openssl_send_async without a prior successful open

Error: Time:Thu Nov 16 07:18:29 2017 File:C:/msys32/home/Kayten/esp/esp-idf/components/azure-iot/sdk/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 475: Failure sending control packet data

Error: Time:Thu Nov 16 07:18:29 2017 File:C:/msys32/home/Kayten/esp/esp-idf/components/azureiot/sdk/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 

Error: mqtt_client_disconnect send failed
-> 07:18:30 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: DENEMEHUB.azure-devices.net/cihaz1/api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.25%20(openssl_compact) | PWD: XXXX | CLEAN: 0

<- 07:18:30 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0

-> 07:18:30 SUBSCRIBE | PACKET_ID: 6 | TOPIC_NAME: devices/cihaz1/messages/devicebound/# | QOS: 1

<- 07:18:30 SUBACK | PACKET_ID: 6 | RETURN_CODE: 1

-> 07:22:21 PINGREQ

<- 07:22:21 PINGRESP

-> 07:26:12 PINGREQ

<- 07:26:12 PINGRESP
 `

**Comment by Patrik-Berglund** [comment]
Hi @omerfatih 

We are also using the ESP32 and have seen the same error, it happens every ~48 minutes when the token is renewed. Would be nice to have this handled in a cleaner way.

Got some other issues tracked here: https://github.com/Azure/azure-iot-sdk-c/issues/269

**Comment by JetstreamRoySprowl** [comment]
The ESP32 tlsio is returning NULL from retrieveoptions, which the SDK interprets as an error instead of "no options available", which may be causing this problem. Fixing this is near the top of my priority list. Thanks for the excellent report!

**Comment by JetstreamRoySprowl** [comment]
The commit from Dec 20 in https://github.com/Azure/azure-iot-pal-esp32 has a fix for the retrieveoptions problem. Please let us know if that fixes this.

**Comment by tameraw** [comment]
@omerfatih - Please reopen if still having issues.

**Comment by jpagliaccio** [comment]
Having the same issue. Was this fixed?

**Comment by omerfatih** [comment]
No, its not fixed


________________________________
Gönderen: jpagliaccio <notifications@github.com>
Gönderildi: 14 Kasım 2018 Çarşamba 17:53
Kime: Azure/azure-iot-pal-esp32
Bilgi: omerfatih; Mention
Konu: Re: [Azure/azure-iot-pal-esp32] ESP32 connection lost between cloud (#2)


Having the same issue. Was this fixed?
