### ISSUE TITLE
Crash tlsio when IOTHUB_CLIENT_CONNECTION_NO_NETWORK

### ISSUE THREAD

**Issue by Resultfactory** [Azure/azure-iot-pal-esp32#3]
Hi,

We have been using the Azure IoT Hub for a while now and have moved from the arduino repository to this one. This repository is much easier to build and looks more stable, but we have noticed some crashes.

We are testing with 3 devices, one of them doesn't have a wifi antenna.
On this device we are seeing a few confirmation message timeouts, which is expected since the wifi connection is less stable. Most of the time the system recovers. Except when ConnectionStatusCallback returns with IOTHUB_CLIENT_CONNECTION_NO_NETWORK.

This is the log containing the backtraces from the 5 occurrences we have logged. [CrashLog](https://pastebin.com/032E2CBx)

Any help would be appreciated!

**Comment by Dmitry4Bh** [comment]
Hi,

Try to change function _enter_open_error_state()_ in file **tlsio_openssl_compact.c** to that code

```
static void enter_open_error_state(TLS_IO_INSTANCE* tls_io_instance)
{
    // save tls_io_instance->on_open_complete because it can be NULL after enter_tlsio_error_state()
    ON_IO_OPEN_COMPLETE on_open_complete = tls_io_instance->on_open_complete;
    void* on_open_complete_context = tls_io_instance->on_open_complete_context;
    enter_tlsio_error_state(tls_io_instance);   
    on_open_complete(on_open_complete_context, IO_OPEN_ERROR);
}

```

It helps in my case when TLS fail in TLSIO_STATE_OPENING_WAITING_DNS state.

**Comment by Resultfactory** [comment]
@Dmitry4Bh This indeed resolves this problem.
Could @JetstreamRoySprowl add this to the repository?

**Comment by JetstreamRoySprowl** [comment]
@Resultfactory @Dmitry4Bh This change just got checked in. Thanks for the input!
