### ISSUE TITLE
Connection Not Accepted: 0x3: Server Unavailable

### ISSUE THREAD

**Issue by Resultfactory** [Azure/azure-iot-pal-esp32#5]
In the past week we have been seeing crashes with error message "Connection Not Accepted: 0x3: Server Unavailable"

I did see a fix for handling the case in the azure-iot-sdk-c repository issues:
https://github.com/Azure/azure-iot-sdk-c/issues/342
https://github.com/Azure/azure-iot-sdk-c/issues/314

When can we expect the sdk submodule to be updated for this repository?

Our crashes on two devices:
**Devkitc**
> Error: Time:Sat Feb  3 05:47:01 2018 File:C:/IoT/BEASTv4/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1350 Connection Not Accepted: 0x3: Server Unavailable
> 
> Guru Meditation Error: Core  0 panic'ed (StoreProhibited)
> . Exception was unhandled.
> Register dump:
> 0x401aaa65: SSL_read at C:/IoT/BEASTv4/esp-idf/components/openssl/library/ssl_lib.c:696
> PC      : 0x401aaa65  PS      : 0x00060830  A0      : 0x80134b01  A1      : 0x3ffe9d20  
> A2      : 0x00000000  A3      : 0x3ffe9d40  A4      : 0x00000040  A5      : 0x00000000  
> A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000003  A9      : 0x3ffe9d00  
> A10     : 0x00000000  A11     : 0x3ffe9d40  A12     : 0x00000004  A13     : 0x00000004  
> A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000008  EXCCAUSE: 0x0000001d  
> 0x4000c2e0: ?? ??:0
> 0x4000c2f6: ?? ??:0
> EXCVADDR: 0x00000038  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  
> 
> 0x401aaa65: SSL_read at C:/IoT/BEASTv4/esp-idf/components/openssl/library/ssl_lib.c:696
> 0x40134afe: dowork_read at C:/IoT/BEASTv4/components/azure-iot/pal/src/tlsio_openssl_compact.c:463
> 0x40134c37: tlsio_openssl_dowork at C:/IoT/BEASTv4/components/azure-iot/pal/src/tlsio_openssl_compact.c:697
> 0x401aa197: xio_dowork at C:/IoT/BEASTv4/components/azure-iot/sdk/c-utility/src/xio.c:165
> 0x4013014b: mqtt_client_dowork at C:/IoT/BEASTv4/components/azure-iot/sdk/umqtt/src/mqtt_client.c:1205
> 0x4012e74d: IoTHubTransport_MQTT_Common_DoWork at C:/IoT/BEASTv4/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:2595
> 0x4012bf11: IoTHubTransportMqtt_DoWork at C:/IoT/BEASTv4/components/azure-iot/sdk/iothub_client/src/iothubtransportmqtt.c:115
> 0x4012958b: IoTHubClient_LL_DoWork at C:/IoT/BEASTv4/components/azure-iot/sdk/iothub_client/src/iothub_client_ll.c:1688
> 0x4010f0f0: AzureIoTHubClient::Task(void*) at C:/IoT/BEASTv4/main/AzureIoTHubClient.cpp:429
> Backtrace: 0x401aaa65:0x3ffe9d20 0x40134afe:0x3ffe9d40 0x40134c37:0x3ffe9da0 0x401aa197:0x3ffe9dc0 0x4013014b:0x3ffe9de0 0x4012e74d:0x3ffe9e10 0x4012bf11:0x3ffe9e40 0x4012958b:0x3ffe9e60 0x4010f0f0:0x3ffe9e90

**Sipy**
> Error: Time:Sat Feb  3 05:41:46 2018 File:C:/IoT/BEASTv4/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:1847 mqtt_client timed out waiting for CONNACK
> 
> Error: Time:Sat Feb  3 05:42:07 2018 File:C:/IoT/BEASTv4/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1354 Connection Not Accepted: 0x3: Server Unavailable
> 
> Guru Meditation Error: Core  0 panic'ed (StoreProhibited)
> . Exception was unhandled.
> Register dump:
> 0x401ac7a9: ?? ??:0
> PC      : 0x401ac7a9  PS      : 0x00060830  A0      : 0x8013585d  A1      : 0x3ffea930  
> A2      : 0x00000000  A3      : 0x3ffea950  A4      : 0x00000040  A5      : 0x00000000  
> A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000003  A9      : 0x3ffea910  
> A10     : 0x00000000  A11     : 0x3ffea950  A12     : 0x00000004  A13     : 0x00000004  
> A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000008  EXCCAUSE: 0x0000001d  
> 0x4000c2e0: ?? ??:0
> 0x4000c2f6: ?? ??:0
> EXCVADDR: 0x00000038  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  
> 
> 0x401ac7a9: ?? ??:0
> 0x4013585a: DestroyInternal at C:/IoT/BEASTv4/components/azure-iot/sdk/c-utility/src/optionhandler.c:193
> 0x40135993: OptionHandler_FeedOptions at C:/IoT/BEASTv4/components/azure-iot/sdk/c-utility/src/optionhandler.c:243
> 0x401abedb: ?? ??:0
> 0x40130e8f: mqttmessage_create at C:/IoT/BEASTv4/components/azure-iot/sdk/umqtt/src/mqtt_message.c:163
> 0x4012f491: cloneMqttOptions at C:/IoT/BEASTv4/components/azure-iot/sdk/umqtt/src/mqtt_client.c:33
> 0x4012cc55: mqtt_notification_callback at C:/IoT/BEASTv4/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:93
> 0x4012a2cf: IoTHubClient_LL_CreateFromConnectionString at C:/IoT/BEASTv4/components/azure-iot/sdk/iothub_client/src/iothub_client_ll.c:1688
> 0x4010f498: AzureIoTHubClient::SendMessage(STATISTICS*) at C:/IoT/BEASTv4/main/AzureIoTHubClient.cpp:429
> Backtrace: 0x401ac7a9:0x3ffea930 0x4013585a:0x3ffea950 0x40135993:0x3ffea9b0 0x401abedb:0x3ffea9d0 0x40130e8f:0x3ffea9f0 0x4012f491:0x3ffeaa20 0x4012cc55:0x3ffeaa50 0x4012a2cf:0x3ffeaa70 0x4010f498:0x3ffeaaa0

**Comment by JetstreamRoySprowl** [comment]
@Resultfactory: The submodules have just been updated with the latest sdk.
