### ISSUE TITLE
Failed DNS lookup causing reboot

### ISSUE THREAD

**Issue by xvinny-zz** [Azure/azure-iot-pal-esp32#9]
Hi,

I'm using GSM (pppos) connection in order to send messages to my Azure IoT Hub server, and sometimes is happening the following error:

```
Info: Failed DNS lookup for Himalaia.azure-devices.net: 202 Guru Meditation Error: Core  0 panic'ed (InstrFetchProhibited)
. Exception was unhandled.
Register dump:
PC      : 0x00000000  PS      : 0x00060030  A0      : 0x8012b489  A1      : 0x3ffbf330  
A2      : 0x3ffd4ae0  A3      : 0x00000001  A4      : 0x3ffd4a18  A5      : 0x3ffd4a18  
A6      : 0x3ffd4a18  A7      : 0x401327c4  A8      : 0x8012b3f9  A9      : 0x3ffbf310  
A10     : 0x00000000  A11     : 0x00000001  A12     : 0x3f418fa0  A13     : 0x0000008b  
A14     : 0x00000001  A15     : 0x3f418f30  SAR     : 0x00000004  EXCCAUSE: 0x00000014  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

Backtrace: 0x00000000:0x3ffbf330 0x4012b486:0x3ffbf350 0x4012b754:0x3ffbf370 0x40168fb7:0x3ffbf390 0x40133768:0x3ffbf3b0 0x40131dbd:0x3ffbf3e0 0x4012f601:0x3ffbf410 0x4012cf3b:0x3ffbf430 0x40114005:0x3ffbf460 0x4011414a:0x3ffbf490 0x40114549:0x3ffbf590 0x40113d3b:0x3ffbf730

Rebooting...
ets Jun  8 2016 00:22:57
```

How could I deal with it?

**Comment by Patrik-Berglund** [comment]
Hi @xvinny 

I have gotten the same error with earlier relases of the azure-iot-sdk-c and azure-iot-pal-esp32.

Crash log:
https://github.com/Patrik-Berglund/esp32-iot-hub/blob/master/CrashLogs/LossOfInternetConnectivity.txt

But it should be fixed now... Stupid question maybe... but are you running the latest releases?

**Comment by xvinny-zz** [comment]
Hi @Patrik-Berglund 

Yes, it is possible. My last update was in january.. I updated it now and I'm gonna test.

**Comment by xvinny-zz** [comment]
@Patrik-Berglund 

I had the luck of getting the same error, but now it didn't reset!! :smile:

**Comment by Patrik-Berglund** [comment]
@xvinny Great! :)

Haven't seen this problem btw? https://github.com/Azure/azure-iot-pal-esp32/issues/6

**Comment by xvinny-zz** [comment]
@Patrik-Berglund no, it didn't happen with me

**Comment by BigPeteB** [comment]
@xvinny It's been a while since this issue was opened. Did you ever get past this problem, or is it still occurring?

**Comment by xvinny-zz** [comment]
No, the problem was related to the Azure server. I'm gonna close the issue.
